name: bulksmsbd_demo
description: Flutter demo app for the bulksmsbd package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  bulksmsbd:
    git:
      url: https://github.com/sofolitltd/bulksmsbd.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
